alias: Dimm lights back to origin
trigger:
  - platform: state
    entity_id:
      - binary_sensor. ## add motion sensor
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.disable_dimming  ## binary helper switch, to disable funcionality when needed instead of turning off automation
    state: 'off'
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.noc ## helper (night) created from Time of day - from 22:00 to 4:00
        state: 'on'  
  - condition: state
    entity_id: light. ## check if light was turned on (add your light or group)
    state: 'on'
action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(''input_number.default_dimm'')|int }}'
    target:
      entity_id: light. ## add light or light group to turn on
mode: single
